--
-- Copyright (c) 2002 by Aldec, Inc. All rights reserved.
--
------------------------------------------------------------------------------------
-- DESCRIPTION   :  Component was generated by Aldec IP CORE Generator, version 3.0
--                  Details: 
--                  Synchronous single ported RAM
--                  Word size : 8 bits
--                  Memory size : 8191 words
--                  Clock (CLK) active : high
--                  Write enable (WE) active : high
-- CREATED       :  2003-7-22, 13:0:18
------------------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.std_logic_unsigned.all;

entity mc8051_ramx is
	port (
		ram_wr_i : in STD_LOGIC;
		clk : in STD_LOGIC;
		reset      : in  std_logic;
		ram_adr_i : in STD_LOGIC_VECTOR(15 downto 0);
		ram_data_i : in STD_LOGIC_VECTOR (7 downto 0);
		ram_data_o : out STD_LOGIC_VECTOR (7 downto 0)
	);
end entity;

--}} End of automatically maintained section

architecture ramx_arch of mc8051_ramx is
	type ramx_mem_type is array (8191 downto 0) of STD_LOGIC_VECTOR (7 downto 0);
	signal ramx_mem : ramx_mem_type;
begin
	process (CLK)
	begin
		if rising_edge(CLK) then
			if (ram_wr_i = '1') then
				ramx_mem(CONV_INTEGER(ram_adr_i)) <= ram_data_i;
			end if;
			ram_data_o <= ramx_mem(CONV_INTEGER(ram_adr_i));
		end if;
	end process;
end architecture;

configuration mc8051_ramx_sim_cfg of mc8051_ramx is 
    for ramx_arch          
    end for; 
end mc8051_ramx_sim_cfg;