--------------------------------------------------------------
 --  Copyright (c) 2011-2021 Anlogic, Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/lenovo/Desktop/MC8051_Version1_6_TDV5/MC8051_Version1_6_TDV5/td_proj/al_ip/pll.vhd
 -- Date	:	2019 11 18
 -- TD version	:	4.6.14314
--------------------------------------------------------------

-------------------------------------------------------------------------------
--	Input frequency:             24.000Mhz
--	Clock multiplication factor: 1
--	Clock division factor:       2
--	Clock information:
--		Clock name	| Frequency 	| Phase shift
--		C0        	| 12.000000 MHZ	| 0  DEG     
--		C1        	| 11.111111 MHZ	| 0  DEG     
--		C2        	| 6.000000  MHZ	| 0  DEG     
--		C3        	| 3.000000  MHZ	| 0  DEG     
--		C4        	| 2.343750  MHZ	| 0  DEG     
-------------------------------------------------------------------------------

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
USE ieee.std_logic_unsigned.ALL;
USE ieee.std_logic_arith.ALL;
LIBRARY eagle_macro;
USE eagle_macro.EAGLE_COMPONENTS.ALL;

ENTITY pll IS
	PORT ( refclk	: IN	STD_LOGIC;
		reset	: IN	STD_LOGIC;
		clk0_out	: OUT	STD_LOGIC;
		clk1_out	: OUT	STD_LOGIC;
		clk2_out	: OUT	STD_LOGIC;
		clk3_out	: OUT	STD_LOGIC;
		clk4_out	: OUT	STD_LOGIC);
END pll;

ARCHITECTURE rtl OF pll IS
	SIGNAL clk0_buf	: STD_LOGIC;
	SIGNAL fbk_wire	: STD_LOGIC;
	SIGNAL clkc_wire	: STD_LOGIC_VECTOR (4 DOWNTO 0);
BEGIN
	bufg_feedback : EG_LOGIC_BUFG
		PORT MAP ( i => clk0_buf, o => fbk_wire );

	pll_inst : EG_PHY_PLL	GENERIC MAP ( DPHASE_SOURCE => "DISABLE",
		DYNCFG => "DISABLE",
		FIN => "24.000",
		FEEDBK_MODE => "NORMAL",
		FEEDBK_PATH => "CLKC0_EXT",
		STDBY_ENABLE => "DISABLE",
		PLLRST_ENA => "ENABLE",
		SYNC_ENABLE => "DISABLE",
		DERIVE_PLL_CLOCKS => "DISABLE",
		GEN_BASIC_CLOCK => "DISABLE",
		GMC_GAIN => 0,
		ICP_CURRENT => 9,
		KVCO => 2,
		LPF_CAPACITOR => 2,
		LPF_RESISTOR => 8,
		REFCLK_DIV => 2,
		FBCLK_DIV => 1,
		CLKC0_ENABLE => "ENABLE",
		CLKC0_DIV => 25,
		CLKC0_CPHASE => 24,
		CLKC0_FPHASE => 0,
		CLKC1_ENABLE => "ENABLE",
		CLKC1_DIV => 27,
		CLKC1_CPHASE => 26,
		CLKC1_FPHASE => 0,
		CLKC2_ENABLE => "ENABLE",
		CLKC2_DIV => 50,
		CLKC2_CPHASE => 49,
		CLKC2_FPHASE => 0,
		CLKC3_ENABLE => "ENABLE",
		CLKC3_DIV => 100,
		CLKC3_CPHASE => 99,
		CLKC3_FPHASE => 0,
		CLKC4_ENABLE => "ENABLE",
		CLKC4_DIV => 128,
		CLKC4_CPHASE => 127,
		CLKC4_FPHASE => 0)
		PORT MAP ( refclk => refclk,
			reset => reset,
			stdby => '0',
			psclk => '0',
			psdown => '0',
			psstep => '0',
			psclksel => "000",
			dclk => '0',
			dcs => '0',
			dwe => '0',
			di => "00000000",
			daddr => "000000",
			fbclk => fbk_wire,
			clkc => clkc_wire);

		clk4_out <= clkc_wire(4);
		clk3_out <= clkc_wire(3);
		clk2_out <= clkc_wire(2);
		clk1_out <= clkc_wire(1);
		clk0_buf <= clkc_wire(0);
		clk0_out <= fbk_wire;

END rtl;
